tasks:
  setup-app:
    name: Build All
    description: builds all code
    command: npm install
    triggeredBy:
      # postEnvironmentStart activates every time the environment is started, e.g. on first start
      - postDevcontainerStart
  start-app:
    name: Start Application
    command: npm start &
    triggeredBy:
      # postEnvironmentStart activates every time the environment is started, e.g. on first start
      # - postEnvironmentStart
      # postEnvironmentStart activates every time the devcontainer is started, e.g. on first start or devcontainer rebuild
      - postDevcontainerStart
    # dependsOn expresses a dependency on another task which ensures that this other task runs before this one.
    dependsOn:
      - setup-app
